/*
 * Set up for future secure state handling, i.e. auth status, logged in user state
 * Code generated by ChatGPT 4.0 (OpenAI), 2024. Prompt: "Help me prepare for secure state handling in a React app"
 */

import { createContext, useContext, useState } from "react";

const AuthContext = createContext();

function getLocalStorage(key, fallback) {
	try {
		const value = localStorage.getItem(key);
		return value ? JSON.parse(value) : fallback;
	} catch {
		return fallback;
	}
}

export function AuthProvider({ children }) {
	const [user, setUser] = useState(() => getLocalStorage("user", null));
	const [isAuthenticated, setIsAuthenticated] = useState(() =>
		getLocalStorage("isAuthenticated", false),
	);

	const register = (email, password) => {
		// TODO: API call to register a user into the backend
		setIsAuthenticated(true);
	};

	const login = (email, password) => {
		// test dummy example account for development purposes
		if (email === "test@example.com" && password === "password") {
			setIsAuthenticated(true);
			setUser({ email });
			localStorage.setItem("isAuthenticated", true);
			localStorage.setItem("user", JSON.stringify({ email }));

			return true;
		}

        alert("Invalid email or password");
        return false;
	};

	const logout = () => {
		setUser(null);
		setIsAuthenticated(false);
		localStorage.removeItem("isAuthenticated");
        localStorage.removeItem("user");
	};

	return (
		<AuthContext.Provider value={{ user, isAuthenticated, login, logout }}>
			{children}
		</AuthContext.Provider>
	);
}

export function useAuth() {
	return useContext(AuthContext);
}
