/*
 * Set up for future secure state handling, i.e. auth status, logged in user state 
 * Code generated by ChatGPT 4.0 (OpenAI), 2024. Prompt: "Help me prepare for secure state handling in a React app"
 */

import { createContext, useContext, useState } from "react";

const AuthContext = createContext();

export function AuthProvider({ children }) {
  const [user, setUser] = useState(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  const register = (email, password) => {
    // TODO: API call to register a user into the backend
    
    setIsAuthenticated(true);
  }

  const login = (userData) => {
    setUser(userData);
    setIsAuthenticated(true);
  };

  const logout = () => {
    setUser(null);
    setIsAuthenticated(false);
  };

  return (
    <AuthContext.Provider value={{ user, isAuthenticated, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  return useContext(AuthContext);
}
