/*
 * Set up for future secure state handling, i.e. auth status, logged in user state
 * Code generated by ChatGPT 4.0 (OpenAI), 2024. Prompt: "Help me prepare for secure state handling in a React app"
 */

import { createContext, useContext, useState } from "react";

const AuthContext = createContext();

export function AuthProvider({ children }) {
	const [user, setUser] = useState(
		() => JSON.parse(localStorage.getItem("user")) || null,
	);
	const [isAuthenticated, setIsAuthenticated] = useState(
		() => JSON.parse(localStorage.getItem("isAuthenticated")) || false,
	);

	const register = (email, password) => {
		// TODO: API call to register a user into the backend
		setIsAuthenticated(true);
	};

	const login = (email, password) => {
		// test dummy example account for development purposes
		if (email === "test@example.com" && password === "password") {
			setIsAuthenticated(true);
			setUser({ email });
      localStorage.setItem("isAuthenticated", true);
      localStorage.setItem("user", JSON.stringify({ email }));
		} else {
			alert("Invalid email or password");
		}
	};

	const logout = () => {
		setUser(null);
		setIsAuthenticated(false);
	};

	return (
		<AuthContext.Provider value={{ user, isAuthenticated, login, logout }}>
			{children}
		</AuthContext.Provider>
	);
}

export function useAuth() {
	return useContext(AuthContext);
}
