"""Final sync before GitHub upload

Revision ID: 9671694b938f
Revises: d6004913302d
Create Date: 2026-04-20 18:51:55.101624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9671694b938f'
down_revision = 'd6004913302d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
